# Generated by Django 5.1.1 on 2024-10-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_product_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'name of order model', 'verbose_name_plural': 'plural name of order model'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name': 'name of product model', 'verbose_name_plural': 'plural name of product model'},
        ),
    ]
